services:
  app:
    image: ghcr.io/xyqyear/mod-version-check
    container_name: mod-version-check
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/backend/data
    environment:
      - APP_NAME=Mod Version Checker
      # - AUTH_TOKEN=your-secret-token
    restart: unless-stopped
